language: node_js
dist: bionic
cache:
  directories:
    - node_modules
script:
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  target_branch: next_app_test_deploy
  on:
    branch: next_app
