language: node_js
node_js:
  - 14
dist: bionic
cache:
  directories:
    - node_modules
script:
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  target_branch: next_app_test_deploy
  local_dir: out
  on:
    branch: next_app
